name: CI

on:
  push:
    branches:
      - 'develop'
  pull_request:

jobs:
  lint:
    name: run lint:js
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.1
          cache: npm
      - name: npm ci
        run: npm ci
      - name: run lint
        run: npm run lint:js -- --max-warnings=0
  # styleLint:
  #   name: run lint:style
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2
  #     - name: setup Node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14.17.1
  #         cache: npm
  #     - name: npm ci
  #       run: npm ci
  #     - name: run lint:style
  #       run: npm run lint:style
